name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1.0.0

    - name: Set up Node.js
      uses: actions/setup-node@v1.2.0
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: npm ci

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.5.6
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
        coverageLocations:
          "${{github.workspace}}/coverage/lcov.info:lcov"